title: Toxip
author: Toxip, Topias Vainio
bio: A fledgling coder, language enthusiast and a deep thinking poet. Dabbling
  with too many things at the same time is his speciality.  
email: toxip@toxip.net
baseurl: "/"
url: "http://toxip.net"
twitter_username: kyuu9sha
github_username:  topiasv

# Build settings
include: ['_pages']
markdown: kramdown
theme: minima

navigation:
  links:
    - title: home
      href: index.html
    - title: blog
      href: blog.html
    - title: cloud
      href: #
    - title: about
      href: #
