title: Toxip
author: Toxip, Topias Vainio
email: toxip@toxip.net
description: >
  Hello I'm toxip, my real name is Topias Vainio. This is my homepage.
  Here you can find information about me, what I do and some services I host.
  Enjoy your stay and I hope you like what you see.
baseurl: "/"
url: "http://toxip.net"
twitter_username: kyuu9sha
github_username:  topiasv

# Build settings
include: ['_pages']
markdown: kramdown
theme: minima

navigation:
  links:
    - title: home
      href: index.html
    - title: blog
      href: blog.html
    - title: cloud
      href: #
    - title: about
      href: #
