title: Toxip
author: Topias Vainio
nickname: toxip
bio: A fledgling coder, language enthusiast and a deep thinking poet. Dabbling
  with too many things at the same time is his speciality.
email: toxip@toxip.net
baseurl: ""
url: "http://toxip.net"
city: "Espoo"
country: "Finland"
twitter_username: kyuu9sha
github_username:  topiasv

# Build settings
include: ['_pages']
markdown: kramdown
theme: minima

social:
  services:
    - service: twitter
      username: kyuu9sha
      href: https://twitter.com/kyuu9sha
    - service: github
      username: topiasv
      href: https://github.com/topiasv
    - service: linkedin
      username: toxip
      href: https://linkedin.com/in/toxip
    - service: telegram
      username: toxip
      href: https://t.me/toxip
    - service: email
      username: toxip@toxip.net
      href: mailto:toxip@toxip.net

navigation:
  links:
    - title: home
      href: index.html
    - title: microblog
      href: notes.html
    - title: about
      href: #